version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    # setting up all the softwares used for installation, building and deploying the application.
    steps:
      - node/install:
          node-version: "16.0"
      - run: node --version
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: "Checking Versions"
          command: |
            node --version
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run api:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run api:build
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Back-End Test
          command: |
            npm run api:test
      - run:
          name: Deploy Back-End EB
          command: |
            npm run api:deploy
      - run:
          name: Deploy Front-End S3
          command: |
            npm run frontend:deploy
workflows:
  basic-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
